### ISSUE TITLE
Example of using the relay remotely

### ISSUE THREAD

**Issue by eldada** [applariat/kubernetes-postfix-relay-host#2]
Your example works perfectly! Thanks!
The usage example still requires connecting to the relay itself (`telnet localhost 2525`).
Can you provide an example of sending the email from a remote host using some command line tools like `curl`, `mailx` or other?

**Comment by cdornsife** [comment]
Use the service to send mail to it from a host in the cluster. https://github.com/applariat/kubernetes-postfix-relay-host/blob/master/kubernetes/tx-smtp-relay-svc.yaml

**Comment by eldada** [comment]
Sorry @cdornsife . I guess I did not explain myself. I'm aware of the service, and also got it working using the service.
I was wondering if there's an example of a client using this relay. Like from a Java app or CLI. It would help testing this in various scenarios.

**Comment by cdornsife** [comment]
https://www.tutorialspoint.com/java/java_sending_email.htm
SMTP clients all do the same thing... send mail to an MTA. Any example code will work.

The relay (port 25) should never be exposed to the outside world (creating an open relay).

**Comment by eldada** [comment]
Thank you.
